# Generated by Django 3.1.5 on 2021-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hack', models.CharField(max_length=200, verbose_name='Yoz:')),
            ],
            options={
                'verbose_name': 'Hack',
                'verbose_name_plural': 'Hacks',
            },
        ),
    ]
