# Generated by Django 3.1.5 on 2021-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='hack',
            field=models.PositiveIntegerField(verbose_name='Yoz:'),
        ),
    ]
