# Generated by Django 3.1.5 on 2021-06-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack_app', '0002_auto_20210627_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='hack',
            field=models.IntegerField(verbose_name='Yoz:'),
        ),
    ]
